# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - jpss-test-function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './TestAzFunction' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CICD_SERVICE_PRINCIPAL }}

      - name: list function apps
        run: |
          az functionapp list
          
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          ls -la ./output
          popd
          
      - name: 'list output dir'
        shell: bash
        run: |
          ls -la '${{ env.AZURE_FUNCTION_APP_PACKAGE_PATH }}'./output
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'jpss-test-function'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          #publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D5807636A26406792F9366457E8CEB7 }}
          
      - name: logout
        run: |
          az logout